### PR TITLE
Make GSit easy to build

### PR DESCRIPTION
**Pull request by Dreeam-qwq**
Use nms repo of CodeMC, so no need to take too much time to use BuildTools to build Spigot version by version.

### CODE REVIEW

**Comment by Gecolay** [comment]
With this "day-one" deploys would not be possible, as the repo only updates a few days after the release of a new version

**Comment by Kichura** [comment]
Wouldn't be it better to just use papermc for compiling instead of spigot's buildtools system in future?

**Comment by Gecolay** [comment]
> Wouldn't be it better to just use papermc for compiling instead of spigot's buildtools system in future?

Could you change the PR to paper's build system?

**Comment by Dreeam-qwq** [comment]
> Wouldn't be it better to just use papermc for compiling instead of spigot's buildtools system in future?

Yes, you can convert project from maven to Gradle, and use `paperweight-userdev` instead of spigotmc's buildtools.

**Pull request closed without merging**
