### PR TITLE
Recode MManager#toFormattedComponent to support colon in front of pattern match #67

### LINKED ISSUE #67: Alternative methode - MManager#toFormattedComponent()
https://github.com/Gecolay/GSit/blob/284f49cf3ce33d2ed5dea51df7a3732930b11367/core/src/main/java/dev/geco/gsit/manager/MManager.java#L129-L135

In the last minutes I wrote code for a private Spigot-Plugin with the same function, which is working with a StringBuilder and a start-position variable, which hasn't any restrictions, like in the mentioned code, where Hex-Colors aren't translated when there is a `:`-symbol in front of the pattern and so doesn't need any if statement in the while loop.

Is there any interest to replace the inbuilt methode? If yes, just write, so I can create a pull request.

~ I like people, who are making their projects OpenSource for such possibilities.

### PR DESCRIPTION
**Pull request by BlockyTheDev**
* Fix #67

### CODE REVIEW

**Comment by BlockyTheDev** [comment]
I saw, that I put the thing with the offset in by mistake, because i developed those methodes for a private plugin with an other pattern, where special letters have to be removed from start and the end. if I should remove this, just write.

**Comment by Gecolay** [comment]
Your commit has the same problem I told you about in the issue:
a string like: `<color:#123456>Test</color>` will be converted to: `color:>Test`.
This method need to support both, spigot and paper format, thats why the `:`-symbol check was there so in the example above, because of the `:`-syombol check this string would get irgnored.

**Comment by BlockyTheDev** [comment]
> Your commit has the same problem I told you about in the issue: a string like: `<color:#123456>Test</color>` will be converted to: `color:>Test`. This method need to support both, spigot and paper format, thats why the `:`-symbol check was there so in the example above, because of the `:`-syombol check this string would get ignored.

Ohh sorry, I missed it while building it into this project for the pull request. I will make another commit to this pr after sleeping.

**Comment by Gecolay** [comment]
The latest commit fixes all this problems!

**Pull request closed without merging**
